on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          command: echo "The key is ${{secrets.SIGNING_KEY}}" | tr '[:lower:]' '[:upper:]'
